name: Run sample code
on:
  push: null
jobs:
  run:
    name: Run sample
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run
      run: |
        bazelisk run //app:api_gen
        bazelisk run //app:load
